title:              Clean Blog
email:              mohammadmusayiab@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Muhammad Musayiab
url:                "https://muhammadmusayiab.github.io/"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
