title:              HackProofed
email:              mohammadmusayiab@gmail.com
description:        Fortifying Your Digital Footprint
author:             Muhammad Musayiab
url:                "https://MuhammadMusayiab.github.io/"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
